import Header from "@/components/Header";
import { Divider, List } from "@mui/material";
import CssBaseline from "@mui/material/CssBaseline";
import Paper from "@mui/material/Paper";
import React from "react";

import ChatroomListItem from "@/components/ChatroomListItem";

const messages = [
  {
    senderId: "1",
    senderName: "Judy",
    content: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person: "/static/images/avatar/5.jpg",
    sendDate: "2022-12-13 22:14",
    totalUnreadMessages: 5,
  },
  {
    senderId: "2",
    senderName: "Chang YU",
    content: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
    person: "/static/images/avatar/1.jpg",
    sendDate: "2022-12-13 22:14",
    totalUnreadMessages: 5,
  },
  {
    senderId: "3",
    senderName: "Jeremy Lin",
    content: "I am try out this new BBQ recipe, I think this might be amazing",
    person: "/static/images/avatar/2.jpg",
    sendDate: "2022-12-13 22:14",
    totalUnreadMessages: 5,
  },
  {
    senderId: "4",
    senderName: "Yes 123",
    content: "I have the tickets to the ReactConf for this year.",
    person: "/static/images/avatar/3.jpg",
    sendDate: "2022-12-13 22:14",
    totalUnreadMessages: 5,
  },
  {
    senderId: "5",
    senderName: "Leotom n jackson ",
    content: "My appointment for the doctor was rescheduled for next Saturday.",
    person: "/static/images/avatar/4.jpg",
    sendDate: "2022-12-13 22:14",
    totalUnreadMessages: 5,
  },
  {
    senderId: "6",
    senderName: "Sandy",
    content: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person: "/static/images/avatar/5.jpg",
    sendDate: "2022-12-13 22:14",
    totalUnreadMessages: 0,
  },
  {
    senderId: "7",
    senderName: "Peterson",
    content: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person: "/static/images/avatar/1.jpg",
    sendDate: "2022-12-13 22:14",
    totalUnreadMessages: 999999,
  },
];

const hideScrollbar = {
  "&::-webkit-scrollbar": {
    display: "none",
  },
  scrollbarWidth: "none",
};

export default function Chatrooms() {
  return (
    <React.Fragment>
      <CssBaseline />
      <Paper square sx={{ pb: "50px", overflowY: "scroll", ...hideScrollbar }}>
        <Header roomName="聊天室列表" onBackButtonClick={() => {}} />
        <List sx={{ mb: 2 }}>
          {messages.map(
            (
              {
                senderId,
                senderName,
                content,
                person,
                sendDate,
                totalUnreadMessages,
              },
              index
            ) => (
              <React.Fragment key={senderId}>
                <ChatroomListItem
                  senderId={senderId}
                  senderName={senderName}
                  content={content}
                  avatarSrc={person}
                  sendDate={sendDate}
                  totalUnreadMessages={totalUnreadMessages}
                  messageType="TEXT"
                />
                {index !== messages.length - 1 && (
                  <Divider variant="inset" component="li" />
                )}
              </React.Fragment>
            )
          )}
        </List>
      </Paper>
    </React.Fragment>
  );
}
